"""Typed controller language, backend-native runtime, and code generators."""

from .compiler import (
    CompilationBundle,
    ControlCompilerError,
    ControlExpression,
    ControlIR,
    FixedPointFormat,
    GeneratedArtifact,
    compile_control,
    compile_resolved_controller,
    generate_c99,
    generate_verilog,
)
from .observer import (
    AffineObserverModel,
    ObserverDerivationError,
)
from .runtime import (
    ControlFrame,
    ControlRuntime,
    ControlRuntimeError,
    ImplicitInputState,
    ObservabilityDiagnostic,
    UnobservableImplicitInputWarning,
    evaluate_control_expression,
    observability_diagnostics,
)
from .specs import (
    ControlSpec,
    ControlSpecError,
    ControlValidationError,
    DerivedSpec,
    ExplicitInputSpec,
    ImplicitInputSpec,
    ModeSpec,
    ObserverSpec,
    OutputSpec,
    ParameterSpec,
    RegisterSpec,
    TransitionSpec,
    control_digest,
    dump_control,
    load_control,
    parse_control,
    validate_control,
)

__all__ = [
    "CompilationBundle",
    "AffineObserverModel",
    "ControlCompilerError",
    "ControlExpression",
    "ControlFrame",
    "ControlIR",
    "ControlRuntime",
    "ControlRuntimeError",
    "ControlSpec",
    "ControlSpecError",
    "ControlValidationError",
    "DerivedSpec",
    "ExplicitInputSpec",
    "FixedPointFormat",
    "GeneratedArtifact",
    "ImplicitInputSpec",
    "ImplicitInputState",
    "ModeSpec",
    "ObserverDerivationError",
    "ObserverSpec",
    "ObservabilityDiagnostic",
    "OutputSpec",
    "ParameterSpec",
    "RegisterSpec",
    "TransitionSpec",
    "UnobservableImplicitInputWarning",
    "compile_control",
    "compile_resolved_controller",
    "control_digest",
    "dump_control",
    "evaluate_control_expression",
    "generate_c99",
    "generate_verilog",
    "load_control",
    "observability_diagnostics",
    "parse_control",
    "validate_control",
]
